### ISSUE TITLE
Migration to version 12.0

### ISSUE THREAD

**Issue by jarmokortetjarvi** [futurable/account-analytic#1]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-12.0

# Modules to migrate

- [ ] account_analytic_default_archived
- [ ] account_analytic_line_partner_from_move
- [ ] account_analytic_name_no_partner
- [ ] account_analytic_tag_disable
- [ ] account_invoice_company_analytic_tags
- [ ] account_invoice_product_analytic_tags
- [ ] account_invoice_product_template_tag_analytic_tags
- [ ] account_invoice_project_analytic_tags
- [ ] account_invoice_used_analytic_accounts
- [ ] account_invoice_used_analytic_tags
- [ ] account_vendor_invoice_analytic_account_to_comment
- [ ] account_vendor_invoice_update_line_analytic_accounts
- [ ] account_vendor_invoice_update_line_analytic_tags
- [ ] company_analytic_tags
- [ ] sale_company_analytic_tags
